unifik_system_backend:
    resource: "@UnifikSystemBundle/Resources/config/routing_backend.yml"
    prefix:   /admin

unifik_system_frontend:
    resource: "@UnifikSystemBundle/Resources/config/routing_frontend.yml"